### ISSUE TITLE
Is there a way to pass Sass options within middleman?

### ISSUE THREAD

**Issue by chanpory** [middleman/middleman#10]
For example, I'd like to set :line_numbers to false, so that line numbers and file paths aren't emitted into the compiled CSS as a comment.

**Comment by iaman** [comment]
Is there any chance we can re-open this issue, considering Compass _itself_ is no longer maintained and the `middleman-compass` gem itself has also been archived (presumably due to Compass no longer being maintained)?

It seems completely absurd that I have to keep a no-longer-maintained `middleman-compass` dependency around *purely* for there to be a means of setting SASS configuration options in my middleman application.

**Comment by tdreyno** [comment]
Well, this ticket is 9 years old.

Sass settings can be set directly in config.rb:

```
set :sass, { stuff }
```

**Comment by tdreyno** [comment]
https://github.com/middleman/middleman/blob/4.x/middleman-core/lib/middleman-core/renderers/sass.rb#L9-L11

**Comment by iaman** [comment]
@tdreyno :O :raised_hands:
