### ISSUE TITLE
Parallelize build steps

### ISSUE THREAD

**Issue by vnorby** [middleman/middleman#1113]
We forked middleman onto a branch and added the "Parallel" gem. We then rewrote two portions of build.rb#execute! with these simple changes:

      css_resources = @app.sitemap.resources.select do |resource|
        resource.ext == ".css"
      end

      Parallel.each(css_resources, :in_processes => 4) do |resource|
        @rack.get(URI.escape(resource.destination_path))
      end

      ...

      Parallel.each(resources, :in_processes => 4) do |resource|
        next if @config[:glob] && !File.fnmatch(@config[:glob], resource.destination_path)

        output_path = render_to_file(resource)

        if should_clean?
          @to_clean.delete(output_path.realpath) if output_path.exist?
        end
      end

Doing so sped up build times by more than 50%. On our middleman project, that was a big deal as it has become quite large. I decided not to do a pull request because I think this would need some configuration options/sensible defaults and testing. But we have our fork running our builds now and it does work magic. I also think other expensive parts of the build can be parallelized with large speed gains and I'm hoping someone more competent than I will pick this issue up and run with it.

**Comment by aviramga** [comment]
@vvasabi Im having the same issue, can you please share your .sh solution? (If you still have it after 3 years :) )

Thanks!

**Comment by vvasabi** [comment]
@aviramga Sorry, I don’t have the script available since I have moved onto another job that doesn’t use Middleman. If memory serves, my setup essentially comes down to organizing the site into subpaths. From there, the script would look something like this:

```
middleman build --no-clean --glob "path1" &
middleman build --no-clean --glob "path2" &
middleman build --no-clean --glob "path3" &
# etc.
wait
```

First, you start multiple `middleman build` processes in the background by adding the `&` character at the end. Then, you call `wait` to wait for them to finish. The number of `middleman build` processes you fork should be close to the number of CPU cores available.

Note that this was not a perfect solution. Each `middleman build` process had to crawl all files within the source directory to populate the sitemap. This could be multiple seconds that each process had to spend churning CPU cycles. Ideally, the sitemap should be generated once and then shared by all build processes. I’m not sure if Middleman now has a better way to parallelize the build process, after all the years.

**Comment by ahoward** [comment]
very clever @vvasabi !
