### ISSUE TITLE
Redcarpet & HAML not working correctly

### ISSUE THREAD

**Issue by Arcovion** [middleman/middleman#1152]
Config

```
set :markdown_engine, :redcarpet
set :markdown, {smartypants: true, underline: true}
```

Haml

```
:markdown
  -- "foo" _bar_ *test*
```

In the generated HTML the markdown is processed but the custom options (underline & smartypants in this example) aren't applied.
Markdown files work fine, it just doesn't work within the `:markdown` HAML filter.

```
module Haml::Filters
  module Markdown
    include Base
    def render text
      md_options = {smartypants: true, underline: true}
      x = Redcarpet::Render::SmartyHTML.new md_options
      y = Redcarpet::Markdown.new x, md_options
      y.render text
    end
  end
end
```

This change I'm currently using adds the options, but isn't using middleman's custom RedcarpetTemplate which has many useful changes:
https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/renderers/redcarpet.rb
and supports stuff like `middleman-syntax` within the markdown.

I think what's happening by default is something like this:

```
module Haml::Filters
  module Markdown
    include Base
    def render text
      ::Tilt['markdown'].new{ text }.render
    end
  end
end
```

But for some reason this isn't applying the custom options.

**Comment by Arcovion** [comment]
This also applies to Kramdown & Slim
```ruby
set :markdown_engine, :kramdown
set :markdown, input: 'GFM'
```
Applies Github Flavoured Markdown to `.md` files but not to the Slim markdown filter.

**Comment by tdreyno** [comment]
@Arcovion Is this still valid? Figured it was a year since any comments

**Comment by Arcovion** [comment]
It is. I prefer hard line wrapping that outputs \<br> tags for every newline (like here in Github), but getting that to work inside the Haml/Slim markdown filters is a pain.

**Comment by HugoGiraudel** [comment]
Confirmed. Still not working properly in `:markdown` filter.

**Comment by cpence** [comment]
Yep, still valid. I've found a way to at least enable smart quotes for Kramdown, though, even in the filter.

In config.rb:

```ruby
set :markdown_engine, :kramdown
set :markdown, smartypants: true, smart_quotes: 'lsquo,rsquo,ldquo,rdquo'

# These overrides hack around the fact that Tilt defaults to dumb quotes in
# Kramdown (and Middleman currently isn't passing in those settings from the
# :markdown settings line above)
Tilt::KramdownTemplate.send(:remove_const, :DUMB_QUOTES)
Tilt::KramdownTemplate.const_set(:DUMB_QUOTES, 'lsquo,rsquo,ldquo,rdquo')
```

**Comment by maxmeyer** [comment]
@cpence Did you try `set :markdown, %w(rdquo rsquo ldquo rdquo)`. I'm using this in `middleman-presentation` to enable smart quotes.

**Comment by cpence** [comment]
No, the internal format in Kramdown is definitely a comma-separated list -- in the source [here,](https://github.com/gettalong/kramdown/blob/0dbdb8c94ebbf6e97edc59864c6fe9f9ba3fbbda/lib/kramdown/options.rb#L468) you can see both the default value and the parser (`simple_array_validator`) that converts the comma-separated list into an array. (I guess passing an array would work, too.)

Anyway, that's not where the bug is here. When you set:

```ruby
set :markdown_engine, :kramdown
set :markdown, smartypants: true, smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
```

Smart quotes are enabled just fine in Markdown files themselves, but are not enabled in the `:markdown` filter inside a HAML file. That seems to be because Tilt (which is being used under the hood by HAML) is initializing Kramdown with a default set of options, rather than passing in the `:markdown` options here. You can see this [in the Tilt source](https://github.com/rtomayko/tilt/blob/master/lib/tilt/kramdown.rb#L19) -- if `options[:smartypants]` isn't set, it forces Kramdown to use dumb quotes. (That's why my override above works, it's making Tilt think that smart quotes are actually dumb quotes.)

I have no idea, though, how to get Middleman to send to Tilt the `:markdown` options that are set in the configuration, so that they'll get picked up when HAML uses Tilt filters...

**Comment by tdreyno** [comment]
Haml didn't used to use Tilt. We already added this "filter through tilt" support for Slim, so maybe that code just needs to be copied to the haml implementation as well.

**Comment by Ch4s3** [comment]
:+1:

**Comment by Arcovion** [comment]
This was finally merged: https://github.com/rtomayko/tilt/pull/250
I think there is some easy way to make this work now, can't check atm.

**Comment by svicalifornia** [comment]
May be related to #1925. If so, I've found origin of the problem and will submit a PR soon. Check #1925 for updates.

**Comment by marnen** [comment]
What is the current status of this issue? Can I help with it?

(For context: I'm using Kramdown both directly and through the Haml `:markdown` filter. I'd like the rendering to be consistent.)

**Comment by marnen** [comment]
Commenting in order to keep this open till we confirm whether it’s been fixed.

**Comment by marnen** [comment]
Keeping this open till we can confirm if it’s been fixed. I’ll try to run some tests, but I don’t know if I will have time.

**Comment by marnen** [comment]
Is this fixed?

**Comment by marnen** [comment]
Keeping this open till we confirm that it’s fixed.
