### ISSUE TITLE
link_to 'http://example.com/index.html' failed when set :relative_links, true

### ISSUE THREAD

**Issue by kidwm** [middleman/middleman#1195]
```
URI::InvalidComponentError at /
bad component(expected absolute path component): ./
```

it seems link_to 'anyhost/*.html' will trigger this to fail.

**Comment by codyrobbins** [comment]
I’m also running into this problem. I have `relative_links` set to true in my configuration but I have some Markdown that contains a few absolute links. If the path of an absolute link happens to match a resource that exists in the Middleman site, whether or not the absolute link contains a host component (i.e., even if it is links to an external site), the Kramdown renderer is attempting to pass the absolute links through `link_to` and it’s dying.

So, for example, if I have the following Markdown

```
[Link](http://google.com/test.html)
```

and I have a file in my Middleman site named `test.html`, then Kramdown attempts to rewrite that absolute link by [passing it through `link_to`](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/renderers/kramdown.rb#L39)—even though that’s an absolute link to an external site that shouldn’t be rewritten.

I tried to work around this by adding `{:relative='false'}` in the Markdown. But `url_for` would have to be changed [here](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/util.rb#L157) to something like `relative = options[:relative] || options['relative'] == 'true'` for this to work. The best solution would be to fix `url_for` so that it doesn’t attempt to rewrite external absolute links. It does raise an exception [here](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/util.rb#L158) if the URL has a host component, but that doesn’t get triggered if `relative_links` is set globally in the configuration rather than passed as an option to `link_to`.

As an aside, all of the automatic link munging stuff Middleman does is super annoying and I really wish there was a way to turn it off across the board. I’m not using `link_to` in any of my templates because it’s an unnecessary level of indirection for my purposes. If this was a full Rails app then URL helpers would gain you things like not having to explicitly specify URLs in `link_to` and `form_for` helpers and whatnot, but in Middleman it just adds another layer of abstraction without any advantages.

For example, there’s absolutely no reason to use `link_to` like this

```
<%= link_to('About', '/about.html') %>
```

when instead you could simply do

```
%a{href: '/about.html'} About
```

It just muddies the waters.

This is all fine and dandy—I don’t need `link_to` so I’m simply not using it in my project. The problem is, however, things like [the line mentioned above](https://github.com/middleman/middleman/blob/v3-stable/middleman-core/lib/middleman-core/renderers/kramdown.rb#L39) where Markdown links are surreptitiously passed through `link_to` anyways. Anywhere I use Markdown in my site the `link_to` helper is covertly applying its weird link munging whether I want it or not and as far as I’m aware there’s no way to disable it.

There are places in my site where for various reasons I want to use relative links and other places I want to use absolute ones. Without being able to turn off this authoritarian application of `link_to` I can’t just write my markup how I need it—it has to all be relative or all be absolute.

For the time being I’ve simply avoided using Markdown for links like this.

**Comment by tdreyno** [comment]
Good research. We'll prioritize fixing this.

**Comment by codyrobbins** [comment]
I’ve made a change to a fork I’m using for my project and it seems to resolve the issue for my case. There’s a lot going on in this `url_for` method so I’m not confident enough to try to put together a pull request, but maybe this will help:

https://github.com/codyrobbins/middleman/commit/16ffdf83a757e8cc6698d773cb280cd634d5118c

**Comment by tdreyno** [comment]
Fixed, will go out in next release or use MM from github for now.
