### ISSUE TITLE
Appending .html to files

### ISSUE THREAD

**Issue by hagenburger** [middleman/middleman#1211]
Middleman tries to add _.html_ to files, if they have no suffix besides preprocessors:
- index.html.erb >> index.html
- index.erb >> index.html

Sometimes this is not useful:
- .htaccess.erb >> .htaccess.html

**Comment by calebeby** [comment]
Is there a way in v4 I can not add double extensions to files? I am using [Prose](http://prose.io/) as an editor, but when it makes new files it only makes *.md files instead of *.html.md. I cannot figure out a way for Middleman to read blog files that are *.md and display them as text/html instead of as text/plain

**Comment by tdreyno** [comment]
@calebeby Sorry, no. But maybe a ticket with Prose to let that product have configurable file names.

**Comment by calebeby** [comment]
@tdreyno What I ended up doing is add this to my `config.rb`:

```ruby
::Rack::Mime::MIME_TYPES[''] = 'text/html'
```
