### ISSUE TITLE
Mount inside a rails app

### ISSUE THREAD

**Issue by Linuus** [middleman/middleman#1394]
Hi!

Is it possible to mount a Middleman app inside rails?

If so, how do I do that?

**Comment by joost** [comment]
I tried mounting the latest Middleman (master) in a Rails app. The goal is to let Middleman render the files on request.

This is my first try:

    # Copied from config.ru from latest middleman
    require 'middleman-core/load_paths'
    ::Middleman.setup_load_paths

    require 'middleman-core'
    require 'middleman-core/rack'

    require 'fileutils'
    FileUtils.mkdir('log') unless File.exist?('log')
    ::Middleman::Logger.singleton("log/middleman_#{ENV['RACK_ENV']}.log")

    ENV['MM_ROOT'] = '/some/middleman/app'
    app = ::Middleman::Application.new
    rack_app = ::Middleman::Rack.new(app).to_app

    run Rack::URLMap.new "/middleman" => rack_app, "/" => Rails.application

This actually seems to work. However the assets are not loaded correctly. Even when configuring with a `http_prefix`:

    set :http_prefix, "/middleman/"

This makes Middleman generate correct HTML (pointing to /middleman/stylesheets/site.css). But this url gives a 404. It seems Middleman receives a ENV['PATH_INFO'] that includes the SCRIPT_NAME (so `/middleman/stylesheets/site.css` instead of `/stylesheets/site.css`) and thus the Middleman `sitemap.find_resource_by_destination_path` can't find it.

Any suggestions?

**Comment by tdreyno** [comment]
Relative assets would be a good fit.

**Comment by joost** [comment]
It is not a case of relative assets (AFAIK) as the final asset url simply returns a 404.
This is the case for all assets, eg.

    http://127.0.0.1:9292/middleman/javascripts/site.css

Middleman returns:

    File Not Found
    /middleman/javascripts/site.css
    If this is an an asset from a gem, add sprockets.import_asset 'site.css' to your config.rb.

See that it includes `/middleman/` here. Where all other requests strip that. Eg.

    http://127.0.0.1:9292/middleman/xavascripts/site.css

Returns:

    File Not Found
    /xavascripts/site.css

**Comment by joost** [comment]
I dug a little deeper and the issue is in middleman-sprockets.
It does a `request_path = URI.decode(File.join(env['SCRIPT_NAME'], env['PATH_INFO']))` (in `Middleman::Sprockes::Environment#call`) where SCRIPT_NAME is '/middleman/stylesheets'.

**Comment by tdreyno** [comment]
Merged. Thanks!

**Comment by maxmeyer** [comment]
@Linuus
Would you mind to document that here? https://github.com/middleman/middleman-guides Might be interesting for others as well.

@tdreyno 
Would you accept that in https://github.com/middleman/middleman-guides?

**Comment by tdreyno** [comment]
@maxmeyer Definitely

**Comment by jkatsnelson** [comment]
I made an example of this, plus auth: https://github.com/jkatsnelson/middleman-rails-auth

**Comment by jkatsnelson** [comment]
@tdreyno I was able to get a very basic middleman 4 app running on rails -- but I can't get the equivalent running with Middleman version 3.3.5 -- I think the problem is that I don't really know how to programmatically call Middleman for that version. A lot of the examples of "just use Middleman.server" aren't working for me. Is there something obvious I am missing?

**Comment by tdreyno** [comment]
@jkatsnelson Can you post how it was working? It might be a regression

**Comment by jkatsnelson** [comment]
Well, after trying a few things with Rails and failing, I moved on to simply trying to [re-produce this gist](https://gist.github.com/polarblau/5817541) with Middleman 3.3.5 -- this is the error I am seeing:

```shell

config.ru:9:in `<main>': undefined method `run' for main:Object (NoMethodError)

```

**Comment by jkatsnelson** [comment]
I was able to get it working actually -- but not with haml. Here is the repo:

https://github.com/jkatsnelson/middleman-rails-haml


and the error:

```shell

[2015-01-23 10:33:08] ERROR SystemStackError: stack level too deep
	/Users/kats/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/haml-4.0.6/lib/haml/helpers/xss_mods.rb:20

```

**Comment by tdreyno** [comment]
I think that might be Rails' Haml over rides conflicting with ours.

**Comment by jkatsnelson** [comment]
Yeah, I ended up using Rack::TryStatic and just mounting the built assets.

**Comment by mebibou** [comment]
@jkatsnelson could you provide some code for this? I am stuck at trying to mount the Middleman in my Rails app. I tried following [your code](https://github.com/jkatsnelson/middleman-rails-haml/) but I have a conflict with `activesupport` version if I use version `3.3.5`. If I use a more recent version, then `Middleman.server` doesn't work since `server` does not exist anymore.

What is the best solution to integrate into a Rails `4.2.6` app? thanks

**Comment by jkatsnelson** [comment]
Sorry, I haven't touched it in a while, good luck!

**Comment by tdreyno** [comment]
I v4 rack file looks like this: https://github.com/middleman/middleman-templates-default/blob/master/optional/config.ru
