### ISSUE TITLE
sprockets.import_asset broken in 4.0.0-rc1

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#1632]
In `config.rb`, I have this line.

```
sprockets.import_asset('bower_components/Font-Awesome/fonts/fontawesome-webfont.woff')
```

I get this error:

```
C:/workspace/my_project/config.rb:50:in `evaluate_configuration!': undefined method
 `import_asset' for #<Sprockets::Environment:0x0000000478f8a8> (NoMethodError)
```

My Gemfile includes:

```
gem 'middleman', '4.0.0.rc.1'
gem 'middleman-sprockets', '4.0.0.rc.1'
```

**Comment by tdreyno** [comment]
This has been removed in favor of Sprockets' built in asset dependency system: https://github.com/rails/sprockets#the-link-directive

We'll definitely document this before final release.

**Comment by johnnyshields** [comment]
I'm a bit confused here. I'd like to copy `bower_components/Font-Awesome/fonts/fontawesome-webfont.eot` to `build/fonts/fontawesome-webfont.eot`. How would I use the `link`

**Comment by maxmeyer** [comment]
@tdreyno Do we need to modify https://middlemanapp.com/advanced/asset_pipeline/ for that? Is relocation still possible? I need that for `middleman-presentation`.

**Comment by maxmeyer** [comment]
~~~ruby
sprockets.import_asset('jquery/dist/jquery.js') do |logical_path|
  Pathname.new('javascripts_new.d') + logical_path
  # => javascripts_new.d/jquery/dist/jquery.js
end
~~~

**Comment by johnnyshields** [comment]
Unless there's a clear way to do this in sprockets I think middleman should keep the `import_asset` capability.

**Comment by tdreyno** [comment]
@johnnyshields I think you'd do something like:

```
//= link "Font-Awesome/fonts/fontawesome-webfont.eot"
```

In your CSS. I was fighting font awesome specifically when writing the Sprockets 3 support. I actually consider their dependency problem a bug for that gem, but the above should work. There are examples in the test suit: https://github.com/middleman/middleman-sprockets/blob/de0673083221132509f17ba02b10c02d080b410d/fixtures/bower-app/source/javascripts/import.js

@maxmeyer Basically, the upgrade to Sprockets 3 had to be a full rewrite due to massive API changes. So it's not so much a matter of "keeping" it as re-implementing it. That code was incredibly complex and non-standard, so using the built-in version with Sprockets makes sense.

It might make more sense to move a generic asset mapping API into middleman core so this kind of "name file X from bower as file Y in middleman" can work even for those who don't use sprockets. I can definitely see the uses.

**Comment by johnnyshields** [comment]
@tdreyno doing what you suggested puts the font awesome files in a nested dir of the `/assets/` folder in the build:

![image](https://cloud.githubusercontent.com/assets/27655/10415914/f647ab94-7039-11e5-83b3-08a48c9898a4.png)

I'd like them to go into the `/fonts/` folder. Is there a way to do this?

**Comment by tdreyno** [comment]
Not currently. What is the use-case for that?

At the very minimum, we could open up an option which we pass the file name and allow the path to be rewritten. But, this is how it works in Rails, so I'd like to avoid doing something different.

**Comment by johnnyshields** [comment]
@tdreyno there are many use cases for controlling where your files appear in your output. In my case, shouldn't be forced to use the arbitrary directory structure of by FontAwesome (or any other 3rd party lib). @maxmeyer mentioned that he has a use case for his middleman-presentation gem.

Rails / Sprockets doesn't have such good support for Bower IMHO. It seemed that `.import_asset` met this requirement, why not leave that in until sprockets provide a suitable alternative.

**Comment by tdreyno** [comment]
The short version is that Sprockets is awful to worth with and there was not a clean way to port our import_asset code to their backwards incompatible new version. I, personally, opt-out of Sprockets in my own projects so my passion for dealing with their repo's constant breaking is pretty low. I'd happily hand this extension off to a new maintainer if someone had the passion and desire to develop and maintain new features while keeping up with Sprockets. For me, though, the easiest thing is to support the bare minimum of features so I can focus on the Middleman core.

As I said above, I believe the basics of this functionality could move into core. Because the ability to map files to new locations easily seems very useful.

**Comment by johnnyshields** [comment]
Agreed that sprockets is a disaster.

I second the idea of adding a basic copy function to the config to Middleman core.

Otherwise I may just write something akin to `Kernel.exec("cp dir/file dir/file2")`

**Comment by maxmeyer** [comment]
> It might make more sense to move a generic asset mapping API into middleman core so this kind of "name file X from bower as file Y in middleman" can work even for those who don't use sprockets. I can definitely see the uses.

Ok. As I definitively need that functionality, how can an API look like? I need something which replaces [this](https://github.com/fedux-org/middleman-presentation/blob/master/middleman-presentation-core/lib/middleman-presentation-core/start.rb#L49-57).

Does it make sense to extend the proxy method by adding adding `replace: true`? This would prevent the need to add `ignore` somewhere else.

~~~ruby
proxy 'original/file/name', 'new/file/name', replace: true
~~~

Or would be something like this better?

~~~ruby
proxy(
  'old/file/name1': 'new/file/name1',
  'old/file/name2': 'new/file/name2'
)
~~~

For me `#proxy` looks like a suitable method to start with. At least it modifies the `Sitemap`. Although it's partly off-topic. @tdreyno What would you suggest to use instead of `sprockets`. I'm not "bound" to this gem, but would prefer to have a ruby solution if there is one. Learning `JavaScript` is on my list, but for now I'm a beginner in this area and have no real need for my daily business as administrator.

**Comment by tdreyno** [comment]
@maxmeyer The frontend world is moving to JS tooling. I'm using Webpack inside of MM v4 for most projects these days. Sucks, but atleast it's not stuck in the past like Sprockets.

As far as an API, I wouldn't overload `proxy`, even if it uses that functionality under the hood. Maybe something like:

```
{
  'old/file/name1': 'new/file/name1',
  'old/file/name2': 'new/file/name2'
}.each do |from, to|
  move_file(from, to)
end
```

Maybe allowing `from` to be outside the project, but likely not watched by the file watcher.

**Comment by johnnyshields** [comment]
@tdreyno just a side note but it would be nice to see a page in the manual explaining how to setup MM with Webpack. There's an Asset Pipeline page so to the amateur user (me) it makes it seem like AP is the recommended approach.

**Comment by maxmeyer** [comment]
@tdreyno 

What about adding `#move` to the object "behind" the `#sitemap`-method instead?

**Comment by tdreyno** [comment]
@johnnyshields will definitely do, as soon as v4 launches.

`Resource#move`? That could work. I guess I assume most people simply write code in `config.rb` and don't put together sitemap extensions. Could do both.

**Comment by tdreyno** [comment]
Added https://github.com/middleman/middleman/commit/3cd84eb4d182614329b6629df9d97909972b5a2c

Only works on assets internal to the site right now, not external paths.

**Comment by maxmeyer** [comment]
Great! :-) And I learned a little bit more how to extend middleman. Thanks.

> Only works on assets internal to the site right now, not external paths.

External paths are outside `source`?

**Comment by maxmeyer** [comment]
Does it makes sense to backport that extension to v3?

**Comment by johnnyshields** [comment]
@tdreyno I've tested your move_file implementation, the syntax is fine, but I think it's important to support directories within the root of the project, not just the `/source` dir. The reason for me is that I put `/bower_components` in the project root, which is the standard for using Bower since the files are fetched externally and it's sort of a cache/temp dir.

**Comment by tdreyno** [comment]
@maxmeyer External paths are "unwatched" paths. So `source`, `data`, `locales`, `lib`, these are all being watched for changes. It's too expensive to do that arbitrarily, and will totally kill the CPU to try to watch things like `node_modules` or `bower_components`.

@johnnyshields That's my plan with "external paths". It'll copy from anywhere. `bower_component`, random files on disc, Dropbox folders, whatever.

**Comment by maxmeyer** [comment]
@tdreyno Sounds good. Thank you for implementing this. Looking at this I think `core` is much more suitable for such a functionality than `middleman-sprockets`.

**Comment by johnnyshields** [comment]
@tdreyno can we specify arbitrary paths to add to the watchlist?

**Comment by johnnyshields** [comment]
and also, thanks for implementing this!

**Comment by tdreyno** [comment]
@johnnyshields in v4, yes, but as I said, it has performance costs
