### ISSUE TITLE
LiveReload: /data/ and /locales/ (the saga continues...)

### ISSUE THREAD

**Issue by johnnyshields** [middleman/middleman#1698]
Following from https://github.com/middleman/middleman/issues/1637

Changes to files in `/data/` and `/locales/` dirs do not trigger live reloads (ie browser doesn't refresh by itself.)

If you manually refresh the browser then changes to both dirs will be reflected.

**Comment by tdreyno** [comment]
In the [LiveReload extension](https://github.com/middleman/middleman-livereload/blob/master/lib/middleman-livereload/extension_3_1.rb) (not a part of core) it basically tries to map a changed file path to a URL. If one exists, it tells LiveReload to reload that path. Not sure there is a way of telling LiveReload to "reload whatever you're looking at" since `data/` and `locales/` could influence every page.

**Comment by johnnyshields** [comment]
@tdreyno I think we should have an "aggressive" option which would cause changes to dirs like /data/ and /locales/ to reload all pages globally, i.e. just cause the browser to refresh on the current URL. My team would use this.

**Comment by tdreyno** [comment]
Sounds great. I'd love patches to `middleman-livereload` since I don't use it and have been looking for users more familiar with how "live reload" should actually work to lead the way.

Core should have everything it needs to notify that extension that data or locales changed, just need to send the right magic bits over the web socket.
