### ISSUE TITLE
Add documentation for rspec

### ISSUE THREAD

**Issue by lbischof** [middleman/middleman#1726]
I would like to test my website with rspec but don't know how. Everything I can find online applies to v3 and doesn't seem to work. I would think testing is something important that should also be documented.

**Comment by tdreyno** [comment]
I know my co-worker @nijotz did this recently. Maybe I can get him to blog about it.

**Comment by dg-ratiodata** [comment]
@tdreyno Or can he update the guide section + javascript? Just as we discussed in #1722

**Comment by nijotz** [comment]
I did it with v3, I can provide an example.  @lbischof would that be useful or are you looking for v4 documentation?

**Comment by lbischof** [comment]
I am looking for v4 documentation. I haven't used rspec before and getting it to work with v4 is probably easier for an experienced user. For example I would like to test my partials and helpers with various sets of data.

**Comment by tdreyno** [comment]
Basically:

```
require 'middleman`

app = ::Middleman::Application.new do
    config[:exit_before_ready] = true
end

expect(app.data.whatever[:something]).to_be true
```

**Comment by dg-ratiodata** [comment]
Alternatively if you can do the following - v3. This approach uses `Capybara` for testing. It's a modified copy of `Capybara`'s rspec integration.

`spec/spec_helper.rb`:

~~~ruby
# encoding: utf-8
$LOAD_PATH << File.expand_path('../../lib', __FILE__)

# Pull in all of the gems including those in the `test` group
require 'bundler'
Bundler.require :default, :test, :development, :debug

# Loading support files
Dir.glob(::File.expand_path('../support/**/*.rb', __FILE__)).each { |f| require_relative f }
~~~

`rspec/support/capybara.rb`:

~~~ruby
require 'capybara'
require 'capybara/dsl'
require 'rspec/core'
require 'capybara/rspec/matchers'
require 'capybara/rspec/features'

RSpec.configure do |config|
  config.include Capybara::DSL
  config.include Capybara::RSpecMatchers

  # A work-around to support accessing the current example that works in both
  # RSpec 2 and RSpec 3.
  fetch_current_example = RSpec.respond_to?(:current_example) ?
    proc { RSpec.current_example } : proc { |context| context.example }

  # The before and after blocks must run instantaneously, because Capybara
  # might not actually be used in all examples where it's included.
  config.after do
    if self.class.include?(Capybara::DSL)
      Capybara.reset_sessions!
      Capybara.use_default_driver
    end
  end
  config.before do
    if self.class.include?(Capybara::DSL)
      example = fetch_current_example.call(self)
      Capybara.current_driver = Capybara.javascript_driver if example.metadata[:js]
      Capybara.current_driver = example.metadata[:driver] if example.metadata[:driver]
    end
  end
end

Capybara.app = Middleman::Application.server.inst do
  set :root, File.expand_path('../../../', __FILE__)
end
~~~

**Comment by nielspetersen** [comment]
We've included this issue in the current issue of the RubyIssues: https://rubyissues.ongoodbits.com/. :gem:

**Comment by sandstrom** [comment]
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while!

@lbischof did the advice in this thread work? If you figured it out feel free to PR a suggested documentation update in https://github.com/middleman/middleman-guides. That would be helpful to others with a similar problem ⛵️ 

Regardless, I think this issue can be closed since it's not an issue with middleman per se, sites like StackOverflow are a better fit for general questions.
