### ISSUE TITLE
Open letter to MM

### ISSUE THREAD

**Issue by woodall** [middleman/middleman#1761]
Hello,

I'm a full-time Rails Developer actively working on my *'Browser JS chops'* like [JS Patterns](http://www.amazon.com/JavaScript-Patterns-Stoyan-Stefanov/dp/0596806752) 

I'm finding a strong trend to encourage me into `node`, `gulp/grunt`, `yeoman` and variations. But I would argue that Middleman accomplish everything with `Gems`, `Asset Pipeline`, and `mm server` so that those other tools can be essentially _ignored_ for the time being.

Am I way off, or is it safe to stick with Middleman, Ruby, and the current tools I know while diving into front-end JS?

_ps - these kinds of open ended opinion questions tend to get flagged on SO so I figured I'd ask here. Hope that's okay_

**Comment by iwarner** [comment]
Yep middleman combines all the great technologies of the modern development process. The only thing I have come across is that sometimes putting middleman into the continuous intergration cycle and building on the fly can be troublesome, i.e. installing the right ruby, bundle and bower on various servers. Probably grunt has the upper had with that.

Otherwise I think middleman excels and rapid development and I use it for all prototype development coupled with my abstraction - http://codeblender.net/

**Comment by woodall** [comment]
@iwarner thanks Ian and I look forward to exploring codeblender, it looks interesting at first pass.

**Comment by tdreyno** [comment]
The `external_pipeline` feature in v4 allows you to combine MM with any external tool. I use it to allow Webpack to handle JS while everything is normal MM
