### ISSUE TITLE
Add bower_components assets from outside source folder?

### ISSUE THREAD

**Issue by rubytastic** [middleman/middleman#1910]
Really love middleman and have some sites build in it ; only I have a really terrible time the last day with it. For the issue you want to add a bower_component asset from your asset pipeline manifest stylesheets.css for example.

It is not possible anyway to include any asset from outside source folder /bower_components like 
```@import "/bower_components/bootstrap/bootstrap.css" for example

```

I could copy the resources to the source/assets/stylesheets folder but that is not a working solution.

How could this be resolved?
Version 4 is not using sprockets anymore: 
https://forum.middlemanapp.com/t/bower-and-stylus-unusable-with-version-4/2084
```

**Comment by rubytastic** [comment]
So Im using 4 so re-adding the sprockets like:

Gemfile:
```
source 'https://rubygems.org'

gem 'middleman', '>= 4.0.0'
gem 'middleman-livereload'
gem 'middleman-sprockets', '~> 4.0.0.rc'```

Then config.rb ( only top initialisation) :
```

activate :directory_indexes
activate :asset_hash
activate :sprockets

sprockets.append_path File.join(root, 'vendor')

set :css_dir,                     'assets/stylesheets'
set :js_dir,                      'assets/javascripts'
set :font_dir,                    'assets/fonts'
set :images_dir,                  'assets/images'
```

Then inside /site/source/assets/stylesheets/main.scss doing sometthing like:

@import "vendor/bootstrap/dist/css/bootstrap.css"
or 
@import "bootstrap/dist/css/bootstrap.css"

Still fails no, bootstrap included.

How should this work? Anyone can please share some light in this?

**Comment by stevenosloan** [comment]
I think that comes down to how sass works, since the stylesheet you're trying to import ends with `.css` sass leaves the import alone to act like a "vanilla" css import. If you're looking to include the contents of that file, you should be able to use a sprockets require:

In `assets/stylesheets/main.css.scss`
```sass
//= require 'bootstrap/dist/css/bootstrap.css'
```

**Comment by rubytastic** [comment]
No this is not working not with sass not .scss which is quite frustrating.
Such a simple case that worked before in 3 why is this such a pain in version 4?

**Comment by stevenosloan** [comment]
Ok, I think I'll need some more info and hopefully we can get to the bottom of it. So, for what I do know (please correct me if I'm wrong):
- using Middleman 4.x & Middleman::Sprockets 4.0.0.rc.x
- activating sprockets & appending your bower path (`vendor`)
- trying it import css out of the bower path into a file in source (`source/assets/stylesheets/main.scss`)

First step, you'll need to change `main.scss` to `main.css.scss` since implied extensions were removed in middleman 4.0.

 After that, can you explain more about what's not working:
- what behavior are you expecting to see?
- what behavior are you seeing -- error messages, file not having expected content, etc

A public repo / gist with a minimal reproduction case would be *super* helpful, but I know those can be a pain sometimes. cheers

**Comment by iwarner** [comment]
When using bootstrap and bower you should be including

    "bootstrap-sass-official" : "",

This way you can import Bootstrap the correct way

    // Bootstrap
    //----------------------------------------------------------------------------//
    @import "bootstrap-sass-official/assets/stylesheets/_bootstrap";

**Comment by iwarner** [comment]
@stevenosloan using @import I believe does not use sprockets, but the included SASS gem? Is that correct?

The sprockets method would be

    #= 

But then you have the issue that variables are not carried as globals

**Comment by stevenosloan** [comment]
@iwarner yeah, IIRC sprockets it just passes off some path stuff to the sass importer (if you're using sprockets). So I think using the bootstrap-sass is probably the way to go -- forgot about that, last I used boostrap it was less only (it's been a while ¯\_(ツ)_/¯ )

**Comment by vvasabi** [comment]
I put together a quick project just to show how Bootstrap can be configured in MM4, completed with Glyphicon support: https://github.com/vvasabi/middleman4-bootstrap. Aside from the need to manually include and activate the middleman-sprockets extension, I didn’t find adding Bootstrap to be too different in MM4 than in 3. Hope that helps.

**Comment by tdreyno** [comment]
Thanks for pitching in, everyone.
