### ISSUE TITLE
External pipeline unnecessarily running a build

### ISSUE THREAD

**Issue by mathie** [middleman/middleman#1916]
I'm trying to speed up my CI build a bit (because that's more exciting than writing new web site copy!) and I've come across what I feel is a misinteraction between middleman's external asset pipeline and the s3_sync extension. I'm using the external pipeline to build assets with gulp (because I hate myself, clearly!). I've got it configured with:

``` ruby
activate :external_pipeline,
  name: :gulp,
  command: "./node_modules/gulp/bin/gulp.js #{build? ? 'build' : 'serve'}",
  source: 'intermediate/'
```

and it's working pretty nicely. The one wee snag is that, when I run `middleman sync` to publish it to S3 with the s3_sync plugin, it kicks off the external pipeline. I'm _not_ asking s3_sync to build the site, because it's always just done that in the preceding step of the CI build.

I've had a wee nosey through the code, and I think this is happening because the external pipeline is always kicked off when the plugin is **activated**. I wonder if it should be 'refactored' so that it happens as a `before_build` hook, or something like that?

The s3_sync plugin sets `config[:mode]` to `:build`, so `build?` evaluates to true (which mostly serves me well, because it means I can distinguish between building and serving, and get gulp to watch for changes, too). Is there a way to distinguish between build and sync in the command's context?

I've opened a [corresponding issue](https://github.com/fredjean/middleman-s3_sync/issues/124) with the middleman-s3_sync extension, just because I'm not really sure where the solution fits best, and who's most motivated to look into it. 😄

**Comment by tdreyno** [comment]
Setting `config[:mode]` to `:config` should work, in that extension. We added a way to opt out of things for simple CLI extensions, but it's not well documented:

https://github.com/middleman/middleman/blob/master/middleman-cli/lib/middleman-cli/config.rb#L25-L31

**Comment by mathie** [comment]
Good to know, thanks! I’ll have a poke around with it today, and see what happens. :)

**Comment by jamesmccann** [comment]
Having a similar problem with external pipeline executing as soon as the plugin is activated. I've got another extension called `css_generator` that I would like to run after the app has loaded `data/` and before the external pipeline runs so that I can inject assets based off the data to webpack. In other words:

- MM bootstraps and loads configuration, `css_generator` and `external_pipeline` both activated
- `css_generator` picks up on a `ready` or `before_build` hook and writes some files to disk
- `external_pipeline` runs as part of `before_build` and runs a webpack build (including the files written above)
- MM build continues as normal

Would moving the external_pipeline to a before_build work for this and other cases? I guess an alternative would be another mechanism for my extension to load the data on activation?

**Comment by tdreyno** [comment]
@jamesmccann Is `css_generator` generating files outside of `source/` that `external_pipeline` is expected to discover?

**Comment by jamesmccann** [comment]
@tdreyno inside `source/` - it generates a directory of css files before the build and then removes them afterwards.

```ruby
class CssGenerator < Middleman::Extension
  expose_to_template :css_for_font_styles
  option :output_dir, nil, 'Directory name for output CSS'

  def before_build
    prepare_output_dir
    output_css_for_report(app.data.report, output_dir)
    output_css_for_pages(app.data.pages, output_dir)
  end

  def after_build
    remove_output_dir!
  end
end
```

**Comment by tdreyno** [comment]
The more canonical way of doing this would be for an extension to generate `Resource`s rather than files. Build won't refresh `source` because it doesn't expect it to change mid-flight.
