### ISSUE TITLE
Error when using jquery-rails Gem

### ISSUE THREAD

**Issue by jbwebesign** [middleman/middleman#1957]
Hey! I've just tried to include jquery-rails within a project for middleman and I seem to be getting an error when the project builds after running `middleman`.

1. Added the following entry to my Gemfile:
`gem 'jquery-rails'`

2. Ran `bundle install`

3. Running `middleman` to build and start server throws the following

```
/Users/myusername/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'jquery-rails'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Rails
```

As far as I know there aren't any issues with the Gem because I was using this Gem on a new Rails project earlier this morning, didn't see any issues. Am I missing an additional step with Middleman or is this a bug?

Thanks very much. Ps - awesome project/tool!

**Comment by sandstrom** [comment]
@jbwebesign this isn't an issue with middleman. Middleman has no association with rails, but your gem (jquery-rails) require rails.

If you need jQuery, simply download the file and include it in your javascript directory.

Typically, these types of questions are a better fit for Stackoverflow (since this isn't a bug in middleman). Feel free to close this issue.

**Comment by jbwebesign** [comment]
Okay cool noted, thanks
