### ISSUE TITLE
config[:partials_dir] is ignored?

### ISSUE THREAD

**Issue by equinusocio** [middleman/middleman#1963]
Inside my `config.rb` i put `config[:partials_dir] = '/app/partials'` (i tried also `partials/`), the partials folder is right inside the app (ex source) and it contains a `_meta.erb` file.
Now in my `app/layouts/layout.erb` i have `<%= partial "meta" %>`. When i run the middleman server i get this error `Error: Could not locate partial: /_meta` because it seems to search the file inside the root folder. If i use `<%= partial "partials/meta" %>` (without the config[:partials_dir]) it works.

I missed something? Thanks.

**Comment by tdreyno** [comment]
It's removed from 4.x: https://middlemanapp.com/basics/upgrade-v4/

**Comment by tdreyno** [comment]
Your solution (always including the full path) is recommends (and easier to follow without the magic IMO too).

**Comment by equinusocio** [comment]
Ok thanks. So i can concatenate a config option inside the partial helper?

Something like 'partial config[:partial] + 'meta''?

**Comment by vvasabi** [comment]
@equinusocio This is a hack (placed in `config.rb`) I use to bring back the v3 partial behaviour:

```ruby
helpers do
  def partial(template, options={}, &block)
    if Dir.exists? File.join(config[:source], config[:partials_dir], File.dirname(template))
      template = File.join(config[:partials_dir], template)
    end
    super(template, options, &block)
  end
end
```

Hope that helps.

**Comment by equinusocio** [comment]
@vvasabi thanks. @tdreyno There is a specific reason of why this conf was removed? 

However, after trying several static sites generators, I'm delighted to middleman and I consider it the best and most complete one.

**Comment by tdreyno** [comment]
@equinusocio We took a look during the planning for v4 at features which required either a lot of code or a lot of documentation. `partials_dir` was one that was surprisingly difficult to implement, since we don't actually own the template layer (we use the Padrino project). We decided the simplified code-base was worth being a little more explicit in the templates. And, after all, the old behavior is only a couple of lines away if you can code a helper for your specific functionality (rather than all possible user functionalities).

Sorry for the inconvenience, hope everything works well for you.
