### ISSUE TITLE
Incremental regeneration support

### ISSUE THREAD

**Issue by inem** [middleman/middleman#2043]
Ideally middleman should regenerate only files, that have been changed, not the whole website.
If website is big, then regeneration of the whole website might take up to 20-40 seconds, which is very inconvenient for development. Also incremental regeneration would speed up build process, when website being generated inside CI system.

As far as I know Jekyll has this feature:
http://idratherbewriting.com/2015/11/04/jekyll-30-released-incremental-regeneration-rocks/

**Comment by iwarner** [comment]
You can do this already, utilise the build Glob, You will need some method to store when last built timestamp and files modified since - then collect them and then run in the build script - should be easy enough to generate in a Rake or Thor file.

    site=CC.XX.com bundle exec middleman build --glob="{404.html,CNAME}"

I use this for Maintenance mode of a site - and then deploy to GitHub

**Comment by inem** [comment]
@iwarner thanks, didn't know about this option! 
Does this mean that I should specify list of changed files manually every time?

**Comment by dosire** [comment]
We tried this but it didn't work for us https://gitlab.com/gitlab-com/www-gitlab-com/issues/1265#note_30507758

**Comment by iwarner** [comment]
@dosire Can you edit your comment here and explain what didnt work please.

For clarity the glob uses the destination path. I am looking at making this the source path instead

**Comment by stanhu** [comment]
@iwarner Yes, we had to do a bit of reverse engineering to learn that we had to use the destination path, which was confusing. This is particularly tricky for middleman-blog posts that get mapped from Markdown to HTML files. Making it the source path would be significantly easier. Would it be possible to get that feature?

**Comment by iwarner** [comment]
@stanhu I got it working with the source path, but this was in context for the Blog, the issue is still that when you want archives, tag clouds, recent articles etc then it still needs to parse almost every page on a blog site. Its very hard to isolate the blog build to one single file at build time.
