### ISSUE TITLE
Question: what is the best way to version my project?

### ISSUE THREAD

**Issue by natke** [middleman/middleman#2066]
I am using this project and it is part of a CI pipeline, and I would like to version the project. (I have a couple of different maintenance branches). What is the best way to do this? (I am not a Ruby expert, but analogies in node would be the version in the package.json, or for Java the version in the pom.xml, or build.gradle

- Ruby version: 2.3.1p112
- Middleman version: 3.3.12
- OS version: ubuntu 16.04

**Comment by tdreyno** [comment]
You want to attach a version to the built site so it can be read? Like a footer or hidden comment?

I would suggest having a variable in your template that gets the current git sha1 and use that.

It's also possible to get the current branch from your CI env variables and use that instead.

**Comment by vvasabi** [comment]
> analogies in node would be the version in the package.json, or for Java the version in the pom.xml, or build.gradle

Personally, I use `bower.json` or `package.json` to annotate a project’s version, whichever is applicable. I’m not a Ruby expert, but I don’t believe, in the Ruby world, there is a standard project metadata file that is comparable to `bower.json`, `package.json`, `pom.xml`, etc. `Gemfile` is one that is found in most Ruby projects, but it only lists dependencies. The common thing I have seen for annotating the version is to have a version file. Here are a couple of examples:

https://github.com/gitlabhq/gitlabhq/blob/master/VERSION
https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/version.rb

Since it doesn’t appear to have a standard, you can do whatever you want to do.

**Comment by natke** [comment]
Thanks for that. I'll add a version.rb.
