### ISSUE TITLE
How to access helpers from middleman console?

### ISSUE THREAD

**Issue by JTronLabs** [middleman/middleman#2076]
[Helpers docs](https://middlemanapp.com/basics/helper-methods/) doesn't mention anything. The [Cli docs](http://www.rubydoc.info/github/middleman/middleman/Middleman/Cli) isn't very helpful either. SO [post 1](http://stackoverflow.com/questions/26163200/middleman-console-how-to-use-it#) and [post 2](http://stackoverflow.com/questions/42144577/how-can-helpers-be-accessed-from-middleman-console) also don't know.

So I enter `middleman console` into cli and attempt to type `my_helper_name(params)` and receive error `NoMethodError: undefined method 'my_helper_name' for #<Middleman::Application:0x50527180>`

**Comment by tdreyno** [comment]
It's not possible to access helpers from the console. They are sandboxed into the Template environment and usually rely on being in a render to work.

If you want to use them, put them in a ruby module or class that can be required in config to appear in the console. Then you can inject those methods into `helpers` which can optionally take a module as the param, instead of a block

**Comment by JTronLabs** [comment]
Aw that stinks, thanks for the help though.

**Comment by ryanburnette** [comment]
I had [the same question](https://stackoverflow.com/q/42144577/2535178). There is a workaround.

```ruby
module PageHelpers
  def thing
    "THING!"
  end
end
```

```sh
$ bundle exec middleman console
irb...> (class Thing; include PageHelpers; end).new.thing
=> "THING!"
```
