### ISSUE TITLE
More documentation for Middleman & SASS, please?

### ISSUE THREAD

**Issue by andy-twosticks** [middleman/middleman#2101]
## Expected behavior and actual behavior

It's subjective I know, but I would expect the documentation to explain how to work with CSS & SASS using Middleman.  It does not appear to.

## Steps to reproduce the problem (from a clean middleman installation)

Try splitting up your SASS into logical units using SASS' `@import`, for example. Out of the box with Middleman, there are extra steps you need to take. As a new Middleman user, I think I could do with quite a bit more explanation.

## Additional information

I can't find any mention of SASS in the documentation at all, and yet it is the way that Middleman serves CSS.  

The page on External Pipelines is good. (I think I need them to get SASS fully working?) But I don't think that it gives you enough information to craft your own pipeline: what do the options actually mean?

- Ruby version:  ~
- Middleman version: ~> 4 
- OS version:  ~

**Comment by vvasabi** [comment]
> Try splitting up your SASS into logical units using SASS' `@import`, for example. Out of the box with Middleman, there are extra steps you need to take.

Unless you use external asset pipeline, which you don’t need to get just SASS working, there shouldn’t be any special steps required to use SASS `@import` in a vanilla Middleman project. Say you have this structure:

```
source/
└── stylesheets/
    ├── _test.scss
    └── main.css.scss
```

In `main.css.scss`, you can just `@import "test";` to have `_test.scss` imported. No additional configuration is required. If something didn’t work the way you expected, then perhaps post your code. Also, [the Middleman forum](https://forum.middlemanapp.com/) is a great place to ask this kind of questions. Hope this helps.

**Comment by andy-twosticks** [comment]
@vvasabi: I can't.  That doesn't work for me.  I just get error #1799, and this seems to be quite common. 

See also: [this](https://github.com/middleman/middleman-syntax/issues/67) issue for the middleman-syntax gem; [this](https://stackoverflow.com/questions/36114325/how-do-i-import-a-scss-erb-file-in-middleman4) stack overflow question.

I am able to work around it by not prepending an underscore to the partial name. But I don't know why this works; presumably an undocumented(!) SASS feature.

But all of this is beside the point of the issue that I raised. If there were documentation for SASS in Middleman, we would be having a very different discussion about this.

**Comment by vvasabi** [comment]
From reading those issues you have linked, are you trying to use `.erb` extension in conjunction with SASS `@import`? If so, it is something that simply won’t work. Since SASS doesn’t call an external processor when `@import`ing a file, a `.erb` SASS file cannot be recognized or rendered by the SASS engine. If this is not the problem you went into, maybe post your code or an example that can reproduce it in a Github repo.

I don’t disagree that the documentation can potentially use some work, but I was able to use SASS `@import` successfully in a vanilla Middleman project created using `middleman init`. If you have a setup, where SASS `@import` does not work, it will be helpful to show what causes it to break, so we can discuss that specifically.

**Comment by andy-twosticks** [comment]
@vvasabi Initially I was trying to follow the instructions for getting markdown-syntax working, which [does in fact assume you can do that](https://github.com/middleman/middleman-syntax#css).

But I reduced the problem to simply importing a partial, and I couldn't get that to work, either.  It sounds as if I should try and create a minimal case, and try to duplicate the problem.  Bear with me and I'll report back here,

**Comment by vvasabi** [comment]
Ah, this paragraph:

> If you want to include this in a larger Sass stylesheet, name it with an underscore (source/stylesheets/_highlighting.css.erb) and include it in your main stylesheet with @import 'highlighting').

I just tried it in my vanilla Middleman v4 project, and it does not work unless the `_` prefix is removed. I suppose I stand corrected that the SASS engine does know how to `@import` a file with a `.erb` extension. The `@import`ed file cannot have a `_` prefix and must have `.css` as part of the extensions; the `@import` statement also needs to include `.css` in the filename.

However, doing this has a significant downside. Due to the lack of the `_` prefix, the `@import`ed file gets generated in the build. If you `ignore` it in `config.rb`, then the `@import` statement fails silently. Although you can have an `after_build` hook that removes the unwanted file, it is cleaner to just avoid creating it in the first place.

Also, it appears to me that the middleman-syntax project has not been updated to support Middleman v4. This might explain why the instruction it has fails to work in v4.

**Comment by vvasabi** [comment]
> SASS partials work out of the box. (Therefore also frameworks like Bourbon, once added to Gemfile?)

Yes, in my experience importing frameworks like Bootstrap or Bourbon work out of the box, once you add them to Gemfile.

**Comment by tdreyno** [comment]
Hmm, this might have happened when Compass was removed from the default project. Might have been doing some fanciness to make these partials work.

**Comment by andy-twosticks** [comment]
@vvasabi 

> I just tried it in my vanilla Middleman v4 project, and it does not work unless the _ prefix is removed.

Well, that's even more confusing; I couldn't get it to work at all, which probably means I was *very* tired when I tried all this, but, ahem, does underline the idea that we could do with some of this in the documentation.

**Comment by vvasabi** [comment]
I think based on @tdreyno's comment above and the side effects you get from forcing `@import` to work with a `.erb` SASS file, it is probably better to assume that this is not intended to be a supported feature. I personally think that mixing Ruby and SASS within a single file is a bad idea, anyways. Not only can the code get messy, but it is also not portable. For example, you won't be able to reuse the same SASS file within a Node.js environment, unless you strip out the Ruby parts.

**Comment by andy-twosticks** [comment]
@vvasabi I actually like my workaround better: why render the CSS dynamically? Just generate it once.

I mean, I know with Middleman the dynamic generation happens at build time; there's no impact on the actual users of my site. But even so.

But of course I am one of these people who, e.g., wondered what the hell use Sprockets was/is, other than adding quite a lot of extra complication in order to save you a couple of seconds during development.  

So perhaps I have an unusual point of view.

**Comment by iwarner** [comment]
@andy-twosticks For some clarity

Middleman uses Tilt and I believe we have Tilt2 in MM4

So all the extensions on the Tilt homepage should be exposed - some have MM wrappers
https://github.com/rtomayko/tilt/

Take note of the required libraries in their documentation also.

This page could do with some love : https://middlemanapp.com/basics/template-engine-options/

**Comment by davewoodall** [comment]
Ah ha! I solved it. *TL;DR* Remove `.css` from the file to `@import` 

---

I thought my issue was because I was not using an eternal pipeline.  My new project, I started with a simple `@import 'partials/nav`
which was in
```
stylesheets/
  partials/nav.scss.css
```
I was getting the following error;

```
SassC::SyntaxError: Error: File to import not found or unreadable: partials/nav.
```
I installed webpack, and that didn't work.

Then, I added underscore, `_nav.scss.css` and that didn't work.

Then, I removed `.css` and it worked! 🎉 

I tested with both underscore `_nav.scss` and without underscore `nav.scss` and both compiled.

So, it seems to me, that if you intend to import, you need to remove `.css`.

For some reason, I _thought_ I read somewhere that we were to have _both_ extensions. 
So, is this desired behavior for `@import`?

**Comment by tdreyno** [comment]
The `.css` is an output extension, if its not becoming a file, it doesn't have one.

I file like at some point Rails and Middleman must have diverged in how we handle naming partials.

**Comment by davewoodall** [comment]
Ah got it. I just picked up a new MM project. Haven't touched it since V3, so I'll do my best to mention any differences I see along the way.  I did notice that `.scss` is missing from [template-engine-options](https://middlemanapp.com/basics/template-engine-options/). I wonder, should it be mentioned for thoroughness? Or, might there be a better place for something like a **using @import** example?

**Comment by tdreyno** [comment]
I think that would be a great addition. It's hard to see things with fresh eyes :)

Would you be willing to contribute a patch to the docs? https://github.com/middleman/middlemanapp.com/blob/master/source/localizable/basics/template-engine-options.html.markdown

I can merge and get it up asap.

**Comment by davewoodall** [comment]
Done. I added a new section, doing my best to explain my specific situation in general terms. I am happy to edit, or remove it if it doesn't fit there..

**Comment by tdreyno** [comment]
Awesome. Going to close this ticket and track the updates there. Thank you
