### ISSUE TITLE
Version 5 abandoned?

### ISSUE THREAD

**Issue by cmer** [middleman/middleman#2400]
I see on that v5-rc1 was released over a year ago, but since, there was only development on the v4 line with semi-frequent releases.

Is v5 abandoned? What’s its status and should I use v4 or v5 for a brand new project?

**Comment by tdreyno** [comment]
Work has been continuing on the main branch, but no gems have been published. Some folks are pointing directly at github rather than rubygems and using that version.

I wouldn't say its abandoned, there is simply not enough time/attention to coordinate, document and release a major version at this time.

Because its not out yet, v5 will likely be incompatible with many third party extensions. If you don't need those, you should be able to start with v5, then bail out back to v4 if you aren't feeling it. Going the other way, from v4 with lots of extensions would likely be more difficult right now.

**Comment by cmer** [comment]
Thanks for the response.

Can we expect most extensions to not be compatible with v5, or just a few? Not sure what the changes are like under the hood.

**Comment by tdreyno** [comment]
The only real change to the core that would effect extensions is the removal of using low-level Rack middleware to also page output. That API isn't really documented or advertised, so I doubt it will effect many popular extensions. Anything under the middleman org (autoprefixer, blog, syntax) will work fine

That said, the most likely difficulty will just be conflicting dependency versions. If the extension says "middleman 4" and not "middleman 4+" then the author will have to republish with a wider version range.

**Comment by smoofles** [comment]
Could this info be added to the README? Might get more people to try v5, or at least understand where its at.
