### ISSUE TITLE
Drop support for EOL Rubies?

### ISSUE THREAD

**Issue by veganstraightedge** [middleman/middleman#2710]
Would you (project owners) be willing to drop support for Ruby < 3.2?

This would match Ruby language's version support strategy and would make ongoing maintenance, contribution, and running Middleman easier, IMO.

https://www.ruby-lang.org/en/downloads/branches

**Comment by tdreyno** [comment]
The goal of this project is to support the ruby versions available when the 4.x series launched. I don't believe long-running apps should be forced to upgrade their ruby version to get access to bug fixes.

If we were to change this, we would need a 5.x release, but I expect there are very few new projects being created in 2024 so that would only serve to keep older projects from getting bug fixes (or require supporting two major versions/branches).
